App\DTO\Request\SaveMessage:
  properties:
    message:
      - NotBlank: ~
      - Type: string
      - Length:
          min: 1
          max: 2000

    datetime:
      - NotBlank: ~
      - GreaterThanOrEqual: -5 min UTC