services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Controller\:
    resource: '%kernel.project_dir%/src/Controller/'
    tags: ['controller.service_arguments']

  App\Validator\:
    resource: '%kernel.project_dir%/src/Validator/'