api_login:
  path: 'login'

api_get_messages:
  controller: App\Controller\MessageController::getMessages
  path: 'messages'
  methods: GET

api_save_message:
  controller: App\Controller\MessageController::saveMessage
  path: 'messages'
  methods: POST

api_user_registration:
  controller: App\Controller\RegistrationController
  path: 'users'
  methods: POST

api_user_me:
  controller: App\Controller\ProfileController
  path: 'users/me'
  methods: GET