parameters:
  app.db.version: '%env(APP_DB_VERSION)%'
  app.db.host: '%env(APP_DB_HOST)%'
  app.db.port: '%env(APP_DB_PORT)%'
  app.db.name: '%env(APP_DB_NAME)%'
  app.db.user: '%env(APP_DB_USER)%'
  app.db.password: '%env(APP_DB_PASSWORD)%'

doctrine:
  dbal:
    default_connection: 'default'
    connections:
      default:
        driver: 'pdo_pgsql'
        host: '%app.db.host%'
        port: '%app.db.port%'
        dbname: '%app.db.name%'
        user: '%app.db.user%'
        password: '%app.db.password%'
        server_version: '%app.db.version%'
        charset: 'utf8'
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
  orm:
    default_entity_manager: 'default'
    auto_generate_proxy_classes: '%kernel.debug%'
    proxy_namespace: 'Proxies'
    proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
    entity_managers:
      default:
        connection: 'default'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          User:
            type: xml
            dir: '%kernel.project_dir%/config/mappings'
            prefix: App\Entity