doctrine_migrations:
  migrations_paths:
    "DoctrineMigrations": "%kernel.project_dir%/config/migrations"
  storage:
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 1024
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'
  organize_migrations: false
  all_or_nothing: false
  check_database_platform: true