parameters:
  default_type: 'about:blank'

  http_exceptions:
    App\Exception\ConstraintValidationException:
      responseCode: 400
      classParams:
        invalidParams: 'errors'
        detail: 'message'
      staticParams:
        type: '%default_type%'
        title: 'Bad request'
        status: 400