security:
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    database:
      entity:
        class: App\Entity\User

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api/v1/
      stateless: true
      anonymous: true
      json_login:
        username_path: email
        check_path: /api/v1/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/v1/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/users$, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
    - { path: ^/api/v1/, roles: IS_AUTHENTICATED_FULLY}