parameters:
  dsn: '%env(resolve:SOCKET_DSN)%'

twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes: ['bootstrap_4_layout.html.twig']
  globals:
    socketDsn: '%dsn%'