version: '3.7'

services:
  websocket:
    build:
      target: dev
    volumes:
      - ../websocket-app:/app
    ports:
      - '8080:8080'

  webserver:
    volumes:
      - ../backend-app/assets:/var/www/assets
    ports:
      - '8099:8081'

  backend:
    volumes:
      - ../backend-app:/var/www

  frontend:
    volumes:
      - ../frontend-app:/app
      - messenger-node-modules:/app/node_modules
    ports:
      - '4200:4200'

  database:
    volumes:
      - messenger-db:/var/lib/postgresql/data
    ports:
      - '3379:5432'

volumes:
  messenger-db:
  messenger-node-modules:
