version: '3.7'

services:
  websocket:
    build:
      target: dev
    volumes:
      - ../websocket-app:/app
    ports:
      - '8080:8080'

  webserver:
    ports:
      - '8099:8081'

  frontend:
    ports:
      - '4200:4200'

  database:
    ports:
      - '3379:5432'
